[[pages]]
path = "pages/home.py"
name = "ë©”ì¸ í™”ë©´"
icon = "ğŸˆ"

[[pages]]
path = "pages/create_char.py"
name = "ìºë¦­í„° ìƒì„±"
icon = "ğŸˆ"

[[pages]]
path = "pages/char_list.py"
name = "ë‚´ ìºë¦­í„° ê´€ë¦¬"
icon = "ğŸˆ"

[[pages]]
path = "pages/modify_char.py"
name = "ë‚´ ìºë¦­í„° ìˆ˜ì •"
icon = "ğŸˆ"

[[pages]]
path = "pages/chatting.py"
name = "ì±„íŒ…í•˜ê¸°"
icon = "ğŸˆ"

[[pages]]
path = "pages/chat_list.py"
name = "ë‚´ ì±„íŒ… ëª©ë¡"
icon = "ğŸˆ"

[[pages]]
path = "pages/login.py"
name = "Login"
icon = "âœ”"